openapi: '3.0.2'
info:
  title: Test API
  version: '1.0'
  description: Description of the Test API.
servers:
  - url: http://localhost:3000
paths:
  /login:
    post:
      requestBody:
        content:
          application/json:
              schema:
                type: object
                properties:
                  email: # the unique user id
                    type: string
                    format: email
                    example: test@gmail.com
                  password: # the password
                    type: string
                    format: password
                    example: lagkage
      responses:
        '201':
          description: OK
  /applications: #Not protected by design
    get:
      responses:
        '200':
          description: OK
  /applications/{id}:
    get:
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
            example: 3
          description: The application ID
      responses:
        '200':
          description: OK
  /posts:
    get:
      responses:
        '200':
          description: OK
  /posts/{id}:
    get:
      security: 
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
            example: 3
          description: The post ID
      responses:
        '200':
          description: OK
components:
  securitySchemes:
     BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - BearerAuth: []

